network: "bcovrin_test"
mediatorinvite: "https://us-east.public.mediator.indiciotech.io/message?oob=eyJAaWQiOiJlOTFkZmYxOC1mYzIwLTRkMjItYjljMi1jMzZhZDI0ZTYwODEiLCJAdHlwZSI6Imh0dHBzOi8vZGlkY29tbS5vcmcvb3V0LW9mLWJhbmQvMS4xL2ludml0YXRpb24iLCJoYW5kc2hha2VfcHJvdG9jb2xzIjpbImh0dHBzOi8vZGlkY29tbS5vcmcvZGlkZXhjaGFuZ2UvMS4wIl0sInNlcnZpY2VzIjpbeyJpZCI6IiNpbmxpbmUiLCJ0eXBlIjoiZGlkLWNvbW11bmljYXRpb24iLCJyZWNpcGllbnRLZXlzIjpbImRpZDprZXk6ejZNa2dTWUJNNjNpSE5laVQyVlNRdTdiYnRYaEdZQ1FyUEo4dUVHdXJiZkdiYmdFIl0sInNlcnZpY2VFbmRwb2ludCI6Imh0dHBzOi8vdXMtZWFzdC5wdWJsaWMubWVkaWF0b3IuaW5kaWNpb3RlY2guaW8vbWVzc2FnZSJ9LHsiaWQiOiIjaW5saW5lIiwidHlwZSI6ImRpZC1jb21tdW5pY2F0aW9uIiwicmVjaXBpZW50S2V5cyI6WyJkaWQ6a2V5Ono2TWtnU1lCTTYzaUhOZWlUMlZTUXU3YmJ0WGhHWUNRclBKOHVFR3VyYmZHYmJnRSJdLCJzZXJ2aWNlRW5kcG9pbnQiOiJ3c3M6Ly93cy51cy1lYXN0LnB1YmxpYy5tZWRpYXRvci5pbmRpY2lvdGVjaC5pby93cyJ9XSwiYWNjZXB0IjpbImRpZGNvbW0vYWlwMSIsImRpZGNvbW0vYWlwMjtlbnY9cmZjMTkiXSwibGFiZWwiOiJDbG91ZCBNZWRpYXRvciJ9"
blecharacteristicwrite: "c3103ded-afd7-477c-b279-2ad264e20e74"
blecharacteristiread: "e6e97879-780a-4c9b-b4e6-dcae3793a3e8"
bleservice: "d2f195b6-2e80-4ab0-be24-32ebe761352f"
blemode: "peripheral" # Options [both, peripheral, central]
blechunkinglimit: 600 # nokia 6.2
mqtt:
  broker: "mqtt://10.50.92.16:1883"
  topic: "topic"
proof:
  attributes:
    - name: 'csn'
      credDef: '54uCo3cqfvxy5anTHTCD2i:3:CL:49073:access'
